/*CRIACAO DA TABELA T_MEDICOS*/

CREATE TABLE T_MEDICOS (

	id INT,
	nome VARCHAR(100) NOT NULL,
	crm VARCHAR(12) NOT NULL,
	telefone VARCHAR(20) NOT NULL,
	email VARCHAR(50) NOT NULL,
	especialidade VARCHAR(15) NOT NULL,
	logradouro VARCHAR(100) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    complemento VARCHAR(100),
    numero VARCHAR(20),
    uf CHAR(2) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    dataCadastro DATE NOT NULL,
    ativo BOOLEAN NOT NULL    /*BOOLEAN = TINYINT(1)*/

);

/*DEFININDO PK E REGRAS DE NEGÓGIO*/

ALTER TABLE T_MEDICOS ADD CONSTRAINT PK_MEDICOS PRIMARY KEY (id);

ALTER TABLE T_MEDICOS MODIFY id INT AUTO_INCREMENT;

ALTER TABLE T_MEDICOS ADD CONSTRAINT UNQ_MEDICOS_EMAIL UNIQUE (email);

ALTER TABLE T_MEDICOS ADD CONSTRAINT UNQ_MEDICOS_TELEFONE UNIQUE (telefone);

ALTER TABLE T_MEDICOS ADD CONSTRAINT CHECK (especialidade IN ('ODONTOLOGIA', 'CARDIOLOGIA', 'NEUROLOGIA', 'ONCOLOGIA', 'PSICOLOGIA'));


/*CRIACAO DA TABELA T_PACIENTES*/

CREATE TABLE T_PACIENTES(

	id INT,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	telefone CHAR(20) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	logradouro VARCHAR(100) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    complemento VARCHAR(100),
    numero VARCHAR(20),
    uf CHAR(2) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    dataCadastro DATE NOT NULL,
    ativo BOOLEAN NOT NULL

);

/*DEFININDO PK E REGRAS DE NEGÓGIO*/

ALTER TABLE T_PACIENTES ADD CONSTRAINT PK_PACIENTES PRIMARY KEY (id);

ALTER TABLE T_PACIENTES MODIFY id INT AUTO_INCREMENT;

ALTER TABLE T_PACIENTES ADD CONSTRAINT UNQ_PACIENTES_TELEFONE UNIQUE (telefone);

ALTER TABLE T_PACIENTES ADD CONSTRAINT UNQ_PACIENTES_EMAIL UNIQUE (email);


/* OBS : A nomenclatura do arquivo .sql a ser salvo na pasta db deve ser como este arquivo. '

V<numero da migration>__<nome que facilita o entendimento da migration>.sql' */
